### PR TITLE
Put template options in 'create new fragment from template' modal

### LINKED ISSUE #23: Put template options in "create new fragment from template" modal

### LINKED ISSUE #26: Deleting a fragment created through a template and editing an existing fragment causes the browser to freeze
Probably will be fixed when ##23 is addressed since there are currently no options to choose from in the "create new fragment from template" modal.

### Steps to reproduce:
1. Create a new fragment from scratch
3. Create a new fragment from template
4. Delete the fragment created from template from the dashboard
5. Try to edit the fragment created from scratch
6. ???
7. Profit.

### PR DESCRIPTION
**Pull request by Donisius**
Closes #23 
Closes #26

The needs to be updated after #27 gets merged, or #27 can update this.

### CODE REVIEW

File: src/components/fragment-preview.tsx [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+		reader.onloadend = () => {
+			const imageUrl: string = reader.result ? reader.result.toString() : '';
+			setPreviewUrl(imageUrl);
+		};
+	};
+
+	useEffect(() => {
+		resetPreview();
+		if (resetPreviewRef) {
+			resetPreviewRef.current = resetPreview;
```
Comment (zvonimirfras) [inline src/components/fragment-preview.tsx:57]: That's weird 🤔 

How about

- rename `resetPreview` to `getPreviewUrl` and export it
   - also make it return the url async instead of setting a var
- take `previewUrl` as optional parameter
   - If not provided, generate it.
- `useEffect` on provided `previewUrl` to update the internal state (which can be renamed to sth like `activePreviewUrl` or sth)

**Review by zvonimirfras — CHANGES_REQUESTED** [review]

File: src/routes/dashboard/fragment-wizard/choose-fragment-modal.tsx [hunk 2]
```diff
@@ -117,7 +170,34 @@ export const ChooseFragmentModal = (props: ChooseFragmentModalProps) => {
...
+				}}>
+					{
+						fragmentsState.fragments.filter((fragment: any) => (
+							fragment.labels && fragment.labels.includes('template')
+						)).map((fragment: any) => (
+							<div className={tileWrapper}>
+								<SelectableTile
+									className={tileStyle}
+									onClick={() => { setSelectedFragment(fragment) }}
+									selected={fragment === selectedFragment}>
```
Comment (zvonimirfras) [inline src/routes/dashboard/fragment-wizard/choose-fragment-modal.tsx:186]:
```suggestion
								className={tileStyle}
								onClick={() => { setSelectedFragment(fragment) }}
								selected={fragment === selectedFragment}>
```

File: src/routes/dashboard/fragment-wizard/choose-fragment-modal.tsx [hunk 3]
```diff
@@ -117,7 +170,34 @@ export const ChooseFragmentModal = (props: ChooseFragmentModalProps) => {
...
+									<div className={tileInnerWrapper}>
+										<FragmentPreview fragment={fragment} />
+										<div>
```
Comment (zvonimirfras) [inline src/routes/dashboard/fragment-wizard/choose-fragment-modal.tsx:189]: needs an empty div?

File: src/routes/dashboard/fragment-wizard/choose-fragment-modal.tsx [hunk 4]
```diff
@@ -117,7 +170,34 @@ export const ChooseFragmentModal = (props: ChooseFragmentModalProps) => {
...
+					lg: 12
+				}}>
+					{
+						fragmentsState.fragments.filter((fragment: any) => (
+							fragment.labels && fragment.labels.includes('template')
+						)).map((fragment: any) => (
+							<div className={tileWrapper}>
+								<SelectableTile
+									className={tileStyle}
+									onClick={() => { setSelectedFragment(fragment) }}
```
Comment (zvonimirfras) [inline src/routes/dashboard/fragment-wizard/choose-fragment-modal.tsx:185]:
```suggestion
									onClick={() => setSelectedFragment(fragment)}
```
?

File: src/utils/fragment-tools.ts [hunk 5]
```diff
@@ -82,3 +82,40 @@ export const hasFragmentStyleClasses = (fragment: any) => {
 
 	return hasComponentStyleClasses(fragment.data);
 };
+
+export const generateUniqueName = (fragments: Array<any>, name: string) => {
```
Comment (zvonimirfras) [inline src/utils/fragment-tools.ts:86]:
```suggestion
export const getUniqueFragmentName = (fragments: Array<any>, name: string) => {
```
?

File: src/routes/dashboard/fragment-tile.tsx [hunk 6]
```diff
@@ -105,53 +83,17 @@ export const FragmentTile = ({
...
 	const resetPreview = async () => {
-		const imageBlob = await getFragmentPreview(fragment, renderProps);
-		const reader = new FileReader();
-		reader.readAsDataURL(imageBlob ? imageBlob : new Blob());
-		reader.onloadend = () => {
-			const imageUrl: string = reader.result ? reader.result.toString() : '';
-			setPreviewUrl(imageUrl);
-		};
+		const url = await getPreviewUrl(fragment);
+		setPreviewUrl((url as string));
```
Comment (zvonimirfras) [inline src/routes/dashboard/fragment-tile.tsx:88]:
```suggestion
		setPreviewUrl(url as string);
```
?

Comment (zvonimirfras) [reply src/routes/dashboard/fragment-tile.tsx:88]: or just

```suggestion
		setPreviewUrl(url);
```

if `getPreviewUrl` resolves to string, which it seems it does.

Comment (zvonimirfras) [reply src/routes/dashboard/fragment-tile.tsx:88]: maybe even oneline it if we don't do any checks?

File: src/routes/dashboard/fragment-tile.tsx [hunk 7]
```diff
@@ -178,7 +120,7 @@ export const FragmentTile = ({
 								onClick={() => { handleModalState(ModalActionType.setDuplicationModal); }}/>
 							<OverflowMenuItem
 								itemText='Reset preview'
-								onClick={resetPreview}/>
+								onClick={() => { resetPreview(); }}/>
```
Comment (zvonimirfras) [inline src/routes/dashboard/fragment-tile.tsx:123]: 🤔

File: src/routes/dashboard/fragment-wizard/choose-fragment-modal.tsx [hunk 8]
```diff
@@ -32,6 +35,47 @@ const fragmentOptions = css`
 		flex-direction: column;
 	}
 `;
+const tileWrapper = css`
```
Comment (Donisius) [inline src/routes/dashboard/fragment-wizard/choose-fragment-modal.tsx:38]: export these because they are similar to the ones from the dashboard tile components

File: src/routes/dashboard/fragment-wizard/choose-fragment-modal.tsx [hunk 9]
```diff
@@ -117,7 +171,32 @@ export const ChooseFragmentModal = (props: ChooseFragmentModalProps) => {
...
+								<SelectableTile
+									className={tileStyle}
+									onClick={() => setSelectedFragment(fragment)}
+									selected={fragment === selectedFragment}>
+									<div className={tileInnerWrapper}>
+										<FragmentPreview fragment={fragment} />
+											<h3>{fragment.title}</h3>
+											<span>
+												{fragment.lastModified ? fragment.lastModified : 'Last modified date unknown'}
+											</span>
```
Comment (Donisius) [inline src/routes/dashboard/fragment-wizard/choose-fragment-modal.tsx:193]: Unindent this

File: src/utils/fragment-tools.ts [hunk 10]
```diff
@@ -82,3 +82,48 @@ export const hasFragmentStyleClasses = (fragment: any) => {
...
+
+	const highestNumber = names
+		.map((n) => Number.parseInt(n.replace(nameRegEx, '$4'), 10))
+		.filter((n) => !isNaN(n)).sort((a, b) => b - a)
+		.shift();
+
+	return `${nameBase} copy ${highestNumber && count < highestNumber ? highestNumber + 1 : count + 1}`;
+};
+
+export const duplicateFragment = (fragments: any, fragment: any, options = {}) => {
```
Comment (Donisius) [inline src/utils/fragment-tools.ts:123]:
```suggestion
export const duplicateFragment = (fragments: any, fragment: any, overrides = {}) => {
```
```suggestion
export const duplicateFragment = (fragments: any, fragment: any, options = {}) => {
```

File: src/routes/dashboard/fragment-tile.tsx (hunk 6 above)
Comment (Donisius) [reply src/routes/dashboard/fragment-tile.tsx:88]: It still complains if I don't include the as string, I can oneline it though

**Review by zvonimirfras — CHANGES_REQUESTED** [review]
`FragmentPreview` could accept additional `setPreviewUrl` prop, drop the active*, update every time there's a fragment change _if_ `setPreviewUrl` is provided.
If needed, we can add another prop to prevent generating preview on fragment change but that might never be needed so let's not for now.

File: src/utils/fragment-tools.ts [hunk 11]
```diff
@@ -84,6 +84,74 @@ export const hasFragmentStyleClasses = (fragment: any) => {
...
+
+	const highestNumber = names
+		.map((n) => Number.parseInt(n.replace(nameRegEx, '$4'), 10))
+		.filter((n) => !isNaN(n)).sort((a, b) => b - a)
+		.shift();
+
+	return `${nameBase} copy ${highestNumber && count < highestNumber ? highestNumber + 1 : count + 1}`;
+};
+
+export const duplicateFragment = (fragments: any, fragment: any, overrides = {}) => {
```
Comment (zvonimirfras) [inline src/utils/fragment-tools.ts:124]: `getFragmentDuplicate` or `newFromFragment` or something similar?

I kinda expected it to take in setFragments and add it to the list, based on the name.

File: src/utils/fragment-tools.ts [hunk 12]
```diff
@@ -84,6 +84,74 @@ export const hasFragmentStyleClasses = (fragment: any) => {
...
+	// copy current fragment and change fragment title
+	let fragmentCopy = JSON.parse(JSON.stringify(fragment));
+	fragmentCopy.title = getUniqueFragmentName(fragments, fragmentCopy.title);
+	fragmentCopy.id = `${Math.random().toString().slice(2)}${Math.random().toString().slice(2)}`;
+	return Object.assign({}, fragmentCopy, overrides);
+};
+
+export const getPreviewUrl = async (fragment: any) => {
```
Comment (zvonimirfras) [inline src/utils/fragment-tools.ts:132]: getFragmentPreviewUrl?

**Review by zvonimirfras — CHANGES_REQUESTED** [review]

File: src/utils/fragment-tools.ts [hunk 13]
```diff
@@ -40,6 +40,10 @@ export const getFragmentPreview = async(fragment: any, props: RenderProps) => {
 	return imageBlob;
 };
 
+export const getFragmentTemplates = (fragments: any) => (
```
Comment (zvonimirfras) [inline src/utils/fragment-tools.ts:43]:
```suggestion
export const getFragmentTemplates = (fragments: any[]) => (
```

**Review by zvonimirfras — APPROVED** [review]
